# Generated by Django 3.2.6 on 2021-08-25 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecoverytoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userstat',
            name='stat_type',
        ),
        migrations.RemoveField(
            model_name='userstat',
            name='user',
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserRecoveryToken',
        ),
        migrations.DeleteModel(
            name='userStat',
        ),
    ]
