# Generated by Django 3.2.6 on 2021-08-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0003_stat_user_userrecoverytoken_userstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='unit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
