# Generated by Django 3.2.6 on 2021-08-28 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0006_user_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='genre',
            new_name='gender',
        ),
    ]
