# Generated by Django 3.2.6 on 2021-08-28 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0007_rename_genre_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.DecimalField(decimal_places=2, default=1.75, max_digits=3),
            preserve_default=False,
        ),
    ]
