# Generated by Django 3.2.6 on 2021-08-30 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0008_auto_20210828_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('access_code', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'scale',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_type',
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('active', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainServices.user')),
            ],
            options={
                'db_table': 'update',
            },
        ),
        migrations.CreateModel(
            name='ScaleUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('update_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainServices.update')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainServices.user')),
            ],
            options={
                'db_table': 'scale_update',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='scale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainServices.scale'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='mainServices.usertype'),
            preserve_default=False,
        ),
    ]
