# Generated by Django 3.2.6 on 2021-08-30 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0009_auto_20210830_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mainServices.usertype'),
        ),
    ]
