# Generated by Django 3.2.6 on 2021-08-30 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0011_alter_user_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Update',
            new_name='UpdateType',
        ),
        migrations.AlterModelTable(
            name='updatetype',
            table='update_type',
        ),
    ]
