# Generated by Django 3.2.6 on 2021-08-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0012_auto_20210830_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatetype',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
