# Generated by Django 3.2.6 on 2021-09-01 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0013_alter_updatetype_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scaleupdate',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mainServices.usertype'),
        ),
    ]
