# Generated by Django 3.2.6 on 2021-09-01 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0014_auto_20210901_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaleupdate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
    ]
