# Generated by Django 3.2.6 on 2021-09-01 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0015_scaleupdate_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaleupdate',
            name='scale',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='mainServices.scale'),
            preserve_default=False,
        ),
    ]
