# Generated by Django 3.2.6 on 2021-09-01 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0017_auto_20210901_0256'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventory',
            table='inventory',
        ),
    ]
