# Generated by Django 3.2.6 on 2021-09-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0018_alter_inventory_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
