# Generated by Django 3.2.6 on 2021-09-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0020_alter_userstat_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scale_name',
            field=models.CharField(default='', max_length=16),
        ),
    ]
