# Generated by Django 3.2.6 on 2021-09-16 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0021_user_scale_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('image_url', models.TextField(null=True)),
                ('sodium', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
                ('cholesterol', models.IntegerField()),
                ('total_time', models.IntegerField()),
                ('portions', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
        migrations.CreateModel(
            name='RecipieType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'recipie_type',
            },
        ),
        migrations.CreateModel(
            name='StepType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'step_type',
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recipie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainServices.recipe')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainServices.steptype')),
            ],
            options={
                'db_table': 'recipe_step',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainServices.ingredient')),
                ('recipie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainServices.recipe')),
            ],
            options={
                'db_table': 'recipe_ingredient',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainServices.recipietype'),
        ),
    ]
