# Generated by Django 3.2.6 on 2021-09-16 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0022_auto_20210916_2127'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipietype',
            table='recipe_type',
        ),
    ]
