# Generated by Django 3.2.6 on 2021-09-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0024_auto_20210916_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cholesterol',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='sodium',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
