# Generated by Django 3.2.6 on 2021-09-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0025_auto_20210916_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipestep',
            name='step_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
