# Generated by Django 3.2.6 on 2021-09-17 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0026_auto_20210917_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipestep',
            old_name='recipie',
            new_name='recipe',
        ),
    ]
