# Generated by Django 3.2.6 on 2021-10-05 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0027_rename_recipie_recipestep_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipieType',
            new_name='RecipeType',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='recipie',
            new_name='recipe',
        ),
    ]
