# Generated by Django 3.2.6 on 2021-10-05 23:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0028_auto_20211005_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('week_number', models.IntegerField()),
                ('week_start', models.DateField(null=True)),
                ('inventory_updated', models.BooleanField(default=True)),
                ('has_stats', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainServices.user')),
            ],
            options={
                'db_table': 'user_week',
            },
        ),
        migrations.CreateModel(
            name='WeekRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('preparation_date', models.DateField(null=True)),
                ('user_evaluation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('visible', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainServices.recipe')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainServices.userweek')),
            ],
            options={
                'db_table': 'week_recipe',
            },
        ),
        migrations.CreateModel(
            name='WeekStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('week_number', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('stat_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainServices.stat')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainServices.userweek')),
            ],
            options={
                'db_table': 'week_stat',
            },
        ),
        migrations.DeleteModel(
            name='userStat',
        ),
    ]
