# Generated by Django 3.2.6 on 2021-10-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0030_auto_20211005_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekrecipe',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
