# Generated by Django 3.2.6 on 2021-10-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0031_weekrecipe_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekRecipeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'week_recipe_type',
            },
        ),
        migrations.RemoveField(
            model_name='weekrecipe',
            name='visible',
        ),
    ]
