# Generated by Django 3.2.6 on 2021-10-13 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0032_auto_20211012_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekrecipe',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mainServices.weekrecipetype'),
            preserve_default=False,
        ),
    ]
