# Generated by Django 3.2.6 on 2021-10-24 19:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0034_alter_weekrecipe_user_evaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekrecipe',
            name='user_evaluation',
        ),
        migrations.AddField(
            model_name='inventory',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainServices.userweek'),
        ),
        migrations.CreateModel(
            name='UserRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('last_evaluation', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainServices.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainServices.user')),
            ],
        ),
    ]
