# Generated by Django 3.2.6 on 2021-10-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0035_auto_20211024_1421'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userrecipe',
            table='user_recipe',
        ),
    ]
