# Generated by Django 3.2.6 on 2021-11-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainServices', '0036_alter_userrecipe_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='original_url',
            field=models.TextField(null=True),
        ),
    ]
